version: '3'

services:
  api:
    entrypoint: npm run start:debug
    build: 
      context: ./api
      dockerfile: ./Dockerfile
    ports:
      - 9229:9229
      - 9000:3000
    volumes:
      - ./api:/app/api
      - ./api/dist:/app/api/dist
      - /app/api/node_modules
    networks:
      - calcstate-net

  web:
    entrypoint: npm run serve
    build: 
      context: ./web
      dockerfile: ./Dockerfile
    ports:
      - 9230:9229
      - 9001:8080
    volumes:
      - ./web:/app/web
      - /app/web/node_modules
      - /app/web/dist
    networks:
      - calcstate-net
  
  arangodb:
    image: arangodb:3.8.4
    ports:
      - 8529:8529
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    environment:
      #- ARANGO_ROOT_PASSWORD=pxtm0222
      #- ARANGO_ROOT_PASSWORD_FILE
      - ARANGO_NO_AUTH=1
      #- ARANGO_RANDOM_ROOT_PASSWORD
    networks:
      - calcstate-net

#  postgresql:
#    image: postgres:14.1
#    ports:
#      - 5432:5432
#    volumes:
#      - ./data:/var/lib/postgresql/data
#    environment:
#      - POSTGRES_USER=test
#      - POSTGRES_PASSWORD=test
#    networks:
#      - calcstate-net
      
  nginx:
    image: nginx
    ports:
      - 9090:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - calcstate-net

networks:
  calcstate-net:
    driver: bridge